# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShowPot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShowPot

  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'

  # UIKit
  pod 'SnapKit'
  pod 'Then'
  
  # UI Related Pods

  # Code Convention
  # pod 'SwiftLint'
  # pod 'SwiftGen'

  # Foundation
  pod 'Alamofire'

  # Social Login
  pod 'GoogleSignIn'

end
